#!/usr/bin/env bash

for f in `git log --numstat HEAD^.. blog|awk '{print $$3}'|egrep '^docs'` ; do \
	aws --profile=starship s3 \
		cp "$$f" s3://starship.tools`echo $$f|sed -e 's/^docs\///'` ; \
done