#!/usr/bin/env bash

echo "Publishing modified content to AWS S3 ..."
for f in `git status|grep modified|awk '{print $$2}'|egrep '^blog/'` ; do \
	aws --profile=starship s3 \
		cp "$$f" s3://starship.tools`echo $$f|sed -e 's/^blog\///'` ; \
done
